# Cluster configuration
cluster:
  name: cluster
  top_level_domain: roybales.com
  storage:
    truenas:
      # TrueNAS server configuration
      server:
        host: truenas.roybales.com
        port: 443
        protocol: https
        allowInsecure: true
      # SSH connection for democratic-csi freenas-ssh-iscsi driver
      sshConnection:
        host: truenas.roybales.com
        port: 22
        username: admin
        password: TRUENAS_SSH_KEY

      # Infisical secret key name (API key, not used for SSH)
      # secretKeys:
        apiKey: TRUENAS_API_KEY
        sshPassword: TRUENAS_SSH_PASSWORD

      # iSCSI configuration
      iscsi:
        targetPortal: "truenas.roybales.com:3260"
        iqnPrefix: "test-cluster"  # Override this per cluster (e.g., "test", "sno", "prod")
        namePrefix: "test-"
        nameSuffix: ""

      # ZFS dataset paths
      zfs:
        datasetParentName: "volume1/test/vols"
        detachedSnapshotsDatasetParentName: "volume1/test/snaps"
        #zvolBlocksize: "16K"
        #zvolCompression: "lz4"
        datasetProperties: {}
        zvolProperties:
          volblocksize: "16K"
          compression: "lz4"
          dedup: "off"
          sync: "standard"

      # Infisical secret key name
      secretKeys:
        apiKey: TRUENAS_API_KEY
        sshPassword: TRUENAS_SSH_PASSWORD

# Democratic CSI Driver configuration
democratic-csi:
  csiDriver:
    name: "org.democratic-csi.truenas-iscsi"

  storageClasses:
    - name: truenas-iscsi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        csi.storage.k8s.io/fstype: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

  volumeSnapshotClasses:
    - name: truenas-iscsi
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      deletionPolicy: Delete
      parameters:
      secrets:
        snapshotter-secret:

  controller:
    rbac:
      openshift:
        privileged: true
    driver:
      image:
        repository: democraticcsi/democratic-csi
        tag: next@sha256:6b758d6faf96f0e96d4b8ac0e240fc290c7bace23c20d78a3eb93781652cb1f1
        pullPolicy: IfNotPresent
    externalAttacher:
      enabled: true
      image:
        registry: registry.k8s.io/sig-storage/csi-attacher
        tag: v4.6.1
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true

  node:
    rbac:
      openshift:
        privileged: true
    #driver:
      #localtimeHostPath: false

  driver:
    existingConfigSecret: democratic-csi-truenas-config
    config:
      # This section is overridden by the ExternalSecret
      # Values here are just for reference/defaults
      # driver: freenas-api-iscsi
      driver: freenas-iscsi
