# Cluster configuration
cluster:
  name: cluster
  top_level_domain: roybales.com
  storage:
    truenas:
      # TrueNAS server configuration
      server:
        host: truenas.roybales.com
        port: 443
        protocol: https
        allowInsecure: true

      # iSCSI configuration
      iscsi:
        targetPortal: "truenas.roybales.com:3260"
        iqnPrefix: "iqn.2005-10.org.freenas.ctl"

      # ZFS dataset paths
      zfs:
        datasetParentName: "volume1/iscsi/test/vols"
        detachedSnapshotsDatasetParentName: "volume1/iscsi/test/snaps"
        zvolBlocksize: "16K"
        zvolCompression: "lz4"

      # Infisical secret key name
      secretKeys:
        apiKey: TRUENAS_API_KEY

# Democratic CSI Driver configuration
democratic-csi:
  csiDriver:
    name: "org.democratic-csi.truenas-iscsi"

  storageClasses:
    - name: truenas-iscsi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        csi.storage.k8s.io/fstype: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

  volumeSnapshotClasses:
    - name: truenas-iscsi
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      deletionPolicy: Delete
      parameters:
      secrets:
        snapshotter-secret:

  controller:
    rbac:
      openshift:
        privileged: true
    driver:
      image:
        repository: democraticcsi/democratic-csi
        tag: next@sha256:6b758d6faf96f0e96d4b8ac0e240fc290c7bace23c20d78a3eb93781652cb1f1
        pullPolicy: IfNotPresent
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true

  node:
    rbac:
      openshift:
        privileged: true
    driver:
      localtimeHostPath: false

  driver:
    existingConfigSecret: democratic-csi-truenas-config
    config:
      # This section is overridden by the ExternalSecret
      # Values here are just for reference/defaults
      driver: freenas-api-iscsi
