spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rbales79/argo-apps
    targetRevision: HEAD

config:
  cluster:
    top_level_domain: roybales.com
    name: hub
    admin_email: rbales79@gmail.com
    timezone: America/New_York
    storage:
      truenas:
        zfs:
          datasetParentName: "volume1/iscsi/hub/vols"
          detachedSnapshotsDatasetParentName: "volume1/iscsi/hub/snaps"
        iscsi:
          namePrefix: "hub-"
        secretKeys:
          apiKey: TRUENAS_API_KEY
          sshPassword: TRUENAS_SSH_PASSWORD
          truenasPassword: TRUENAS_PASSWORD
      config:
        storageClassName: truenas-iscsi
      media:
        nfs:
          server: truenas.roybales.com
          path: /mnt/volume1/media

  plex:
    network:
      ip: 192.168.1.225

  emqx:
    network:
      ip: 192.168.1.226

  certificates:
    letsencrypt:
      issuer: production

  externalSecrets:
    secret: infisical-auth-secret
    infisical:
      projectSlug: hub
      environmentSlug: prod

  network:
    lan:
      defaultGateway: 192.168.1.1
