apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amd-gpu-device-plugin
  labels:
    app.kubernetes.io/name: amd-gpu-device-plugin
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
  - update
