---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.application.name | lower | replace " " "-" }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name | lower | replace " " "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: terraform-enterprise-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        encryption-password: "{{ `{{ .TERRAFORM_ENTERPRISE_ENCRYPTION_PASSWORD }}` }}"
        admin-password: "{{ `{{ .TERRAFORM_ENTERPRISE_ADMIN_PASSWORD }}` }}"
  dataFrom:
    - find:
        path: TERRAFORM_ENTERPRISE_ENCRYPTION_PASSWORD
    - find:
        path: TERRAFORM_ENTERPRISE_ADMIN_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-license
  namespace: {{ .Values.application.name | lower | replace " " "-" }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name | lower | replace " " "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: terraform-enterprise-license
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        license: "{{ `{{ .TERRAFORM_ENTERPRISE_LICENSE }}` }}"
  dataFrom:
    - find:
        path: TERRAFORM_ENTERPRISE_LICENSE
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.application.name | lower | replace " " "-" }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name | lower | replace " " "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: terraform-enterprise-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .TERRAFORM_ENTERPRISE_DB_PASSWORD }}` }}"
  dataFrom:
    - find:
        path: TERRAFORM_ENTERPRISE_DB_PASSWORD
