---
{{- if .Values.gatus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gatus-ep
  namespace: gatus
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: {{ .Values.application.name }}
        group: {{ .Values.application.group }}
        url: "https://{{ tpl .Values.route.hostname . }}"
        interval: {{ .Values.gatus.interval }}
        client:
          insecure: false
          timeout: 10s
        conditions:
          {{- range .Values.gatus.conditions }}
          - {{ . | quote }}
          {{- end }}
        alerts:
          - type: discord
{{- end }}
