---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.application.name | lower | replace " " "-" }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name | lower | replace " " "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.main.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.application.name | lower | replace " " "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.main.ports.http.port }}
      targetPort: {{ .Values.service.main.ports.http.targetPort }}
      protocol: TCP
    - name: https
      port: {{ .Values.service.main.ports.https.port }}
      targetPort: {{ .Values.service.main.ports.https.targetPort }}
      protocol: TCP
    - name: console
      port: {{ .Values.service.main.ports.console.port }}
      targetPort: {{ .Values.service.main.ports.console.targetPort }}
      protocol: TCP
