---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.application.name | lower | replace " " "-" }}
  namespace: {{ .Values.application.name | lower | replace " " "-" }}
  labels:
    app.kubernetes.io/name: {{ .Values.application.name | lower | replace " " "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
