---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.acm.namespace }}
  labels:
    name: {{ .Values.acm.namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: multicluster-engine
  namespace: {{ .Values.acm.namespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-engine
  namespace: {{ .Values.acm.namespace }}
spec:
  channel: {{ .Values.acm.channel }}
  installPlanApproval: {{ .Values.acm.installPlanApproval }}
  name: multicluster-engine
  source: {{ .Values.acm.source }}
  sourceNamespace: {{ .Values.acm.sourceNamespace }}
