cluster:
  top_level_domain: roybales.com
  name: cluster
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: truenas.roybales.com
        path: /mnt/volume1/media

application:
  name: Lidarr
  group: Media
  icon: music-box
  iconColor: ""
  image: "https://raw.githubusercontent.com/Lidarr/Lidarr/develop/Logo/400.png"
  description: "Music collection manager"
  port: 8686
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/home-operations/lidarr
      # renovate: datasource=docker depName=ghcr.io/home-operations/lidarr versioning=semver
      tag: 2.14.5.4836
      pullPolicy: IfNotPresent

# Gatus monitoring
gatus:
  enabled: true
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 3000"
