cluster:
  top_level_domain: &tld roybales.com
  name: &cluster openshift
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
    config:
      storageClassName: truenas-iscsi
    media:
      nfs:
        server: truenas.roybales.com
        path: /mnt/volume1/media

application:
  name: Radarr
  group: Media
  icon: cbi:radarr
  iconColor: ""
  image: "https://avatars.githubusercontent.com/u/25025331"
  description: "Movie management"
  port: &port 7878
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/home-operations/radarr
      # renovate: datasource=docker depName=ghcr.io/home-operations/radarr versioning=loose
      tag: 5.28.0.10205
      pullPolicy: IfNotPresent
    env:
      RADARR__APP__INSTANCENAME: Radarr
      RADARR__APP__THEME: dark
      RADARR__AUTH__METHOD: External
      RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
      RADARR__LOG__DBENABLED: "False"
      RADARR__LOG__LEVEL: info
      RADARR__SERVER__PORT: *port
      RADARR__UPDATE__BRANCH: develop
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes

# Gatus monitoring
gatus:
  enabled: false
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 3000"
