apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delay-after-storage
  annotations:
    argocd.argoproj.io/sync-wave: "75"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: delay
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting 2 minutes after storage deployment..."
          sleep 120
          echo "Delay complete, proceeding to application deployment"
      restartPolicy: Never
      serviceAccountName: default
  backoffLimit: 1
