apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delay-after-security
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: delay
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting 1 minute after External Secrets Operator deployment..."
          sleep 60
          echo "Delay complete, proceeding to storage deployment"
      restartPolicy: Never
      serviceAccountName: default
  backoffLimit: 1
