apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-wait-for-eso
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-wait-for-eso
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-wait-for-eso
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-wait-for-eso
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-wait-for-eso
  namespace: openshift-gitops
