---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.pods.main.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
            app.kubernetes.io/controller: main
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/name: {{ .Release.Name }}
        spec:
          enableServiceLinks: false
          automountServiceAccountToken: true
          restartPolicy: Never
          containers:
            - name: app
              image: {{ .Values.pods.main.containers.app.image.repository }}:{{ .Values.pods.main.containers.app.image.tag }}
              imagePullPolicy: IfNotPresent
              env:
              - name: TZ
                value: {{ .Values.cluster.timezone }}
              envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
              args:
                - sync
              volumeMounts:
              - name: config-file
                mountPath: /config/recyclarr.yaml
                subPath: recyclarr.yaml
                readOnly: true
              - name: config
                mountPath: /config
              - name: tmp-dir
                mountPath: /tmp
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
          volumes:
          - name: config-file
            configMap:
              name: {{ .Release.Name }}
          - name: config
            emptyDir: {}
          - name: tmp-dir
            emptyDir: {}
