cluster:
  top_level_domain: example.com
  name: cluster
  storage:
    democratic-csi:
      httpConnection:
        host: nas.roybales.com
        port: 5000
      iscsi:
        targetPortal: nas.roybales.com
    config:
      storageClassName: synology-iscsi

democratic-csi:
  driver:
    existingConfigSecret: democratic-csi-config
    config:
      driver: synology-iscsi
      iscsi:
        lunTemplate:
          description: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

  csiDriver:
    name: "org.democratic-csi.iscsi-synology"

  node:
    rbac:
      openshift:
        privileged: true
    driver:
      localtimeHostPath: false

  controller:
    rbac:
      openshift:
        privileged: true
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true

  storageClasses:
    - name: synology-iscsi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

  volumeSnapshotClasses:
    - name: synology-iscsi
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      deletionPolicy: Delete
      parameters:
      secrets:
        snapshotter-secret:
