{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}
{{- end }}
