---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-truenas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: freenas-iscsi
          httpConnection:
            protocol: {{ .Values.cluster.storage.truenas.server.protocol }}
            host: {{ .Values.cluster.storage.truenas.server.host }}
            port: {{ .Values.cluster.storage.truenas.server.port }}
            allowInsecure: {{ .Values.cluster.storage.truenas.server.allowInsecure }}
            apiVersion: 2
          sshConnection:
            host: {{ .Values.cluster.storage.truenas.sshConnection.host | quote }}
            port: {{ .Values.cluster.storage.truenas.sshConnection.port | default 22 }}
            username: {{ .Values.cluster.storage.truenas.sshConnection.username | quote }}
            password: {{ `{{ .TRUENAS_SSH_PASSWORD }}` | quote }}
          zfs:
            datasetParentName: {{ .Values.cluster.storage.truenas.zfs.datasetParentName | quote }}
            detachedSnapshotsDatasetParentName: {{ .Values.cluster.storage.truenas.zfs.detachedSnapshotsDatasetParentName | quote }}
            zvolBlocksize: {{ .Values.cluster.storage.truenas.zfs.zvolBlocksize | quote }}
            zvolCompression: {{ .Values.cluster.storage.truenas.zfs.zvolCompression | quote }}
            thinProvision: true
          iscsi:
            baseiqn: iqn.2000-01.com.truenas:csi.
            iqnPrefix: {{ .Values.cluster.storage.truenas.iscsi.iqnPrefix | quote }}
            namePrefix: {{ .Values.cluster.storage.truenas.iscsi.namePrefix | quote }}
            nameSuffix: {{ .Values.cluster.storage.truenas.iscsi.nameSuffix | quote }}
            targetPortal: {{ .Values.cluster.storage.truenas.iscsi.targetPortal | quote }}
            targetPortals: []
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup: ""
            extentUseThinProvisioning: true
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 4096
            extentRpm: "SSD"
            discoveryCHAPAuth: false
            chap: "disabled"
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: {{ .Values.cluster.storage.truenas.secretKeys.apiKey }}
    - secretKey: TRUENAS_SSH_PASSWORD
      remoteRef:
        key: {{ .Values.cluster.storage.truenas.secretKeys.sshPassword }}
