---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-truenas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            protocol: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "protocol" }}
            host: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "host" }}
            port: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "port" }}
            apiKey: {{ `"{{ .TRUENAS_API_KEY }}"` }}
            allowInsecure: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "allowInsecure" }}
          zfs:
            datasetParentName: {{ index .Values "democratic-csi" "driver" "config" "zfs" "datasetParentName" }}
            detachedSnapshotsDatasetParentName: {{ index .Values "democratic-csi" "driver" "config" "zfs" "detachedSnapshotsDatasetParentName" }}
            zvolBlocksize: {{ index .Values "democratic-csi" "driver" "config" "zfs" "zvolBlocksize" }}
            zvolCompression: {{ index .Values "democratic-csi" "driver" "config" "zfs" "zvolCompression" }}
            thinProvision: {{ index .Values "democratic-csi" "driver" "config" "zfs" "thinProvision" }}
          iscsi:
            iqnPrefix: {{ index .Values "cluster" "storage" "democratic-csi" "iscsi" "iqnPrefix" }}
            targetPortal: {{ index .Values "cluster" "storage" "democratic-csi" "iscsi" "targetPortal" | quote }}
            targetPortals: []
            targetGroups:
              - targetGroupPortalGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupPortalGroup" }}
                targetGroupInitiatorGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupInitiatorGroup" }}
                targetGroupAuthType: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupAuthType" }}
                targetGroupAuthGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupAuthGroup" | quote }}
            extentUseThinProvisioning: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentUseThinProvisioning" }}
            extentDisablePhysicalBlocksize: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentDisablePhysicalBlocksize" }}
            extentBlocksize: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentBlocksize" }}
            extentRpm: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentRpm" | quote }}
            discoveryCHAPAuth: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "discoveryCHAPAuth" }}
            chap: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "chap" | quote }}
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: TRUENAS_API_KEY
