---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-truenas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: {{ .Values.cluster.storage.truenas.driver }}
          {{- if .Values.cluster.storage.truenas.instance_id }}
          instance_id: {{ .Values.cluster.storage.truenas.instance_id | quote }}
          {{- end }}
          httpConnection:
            protocol: {{ .Values.cluster.storage.truenas.httpConnection.protocol }}
            host: {{ .Values.cluster.storage.truenas.httpConnection.host }}
            port: {{ .Values.cluster.storage.truenas.httpConnection.port }}
            {{- if .Values.cluster.storage.truenas.httpConnection.apiKey }}
            apiKey: {{ `{{ .TRUENAS_API_KEY }}` | quote }}
            {{- else }}
            username: {{ .Values.cluster.storage.truenas.httpConnection.username }}
            password: {{ `{{ .TRUENAS_PASSWORD }}` | quote }}
            {{- end }}
            allowInsecure: {{ .Values.cluster.storage.truenas.httpConnection.allowInsecure }}
            {{- if .Values.cluster.storage.truenas.httpConnection.apiVersion }}
            apiVersion: {{ .Values.cluster.storage.truenas.httpConnection.apiVersion }}
            {{- end }}
          sshConnection:
            host: {{ .Values.cluster.storage.truenas.sshConnection.host | quote }}
            port: {{ .Values.cluster.storage.truenas.sshConnection.port }}
            username: {{ .Values.cluster.storage.truenas.sshConnection.username | quote }}
            {{- if .Values.cluster.storage.truenas.sshConnection.privateKey }}
            privateKey: {{ `{{ .TRUENAS_SSH_PRIVATEKEY }}` | quote }}
            {{- else }}
            password: {{ `{{ .TRUENAS_SSH_PASSWORD }}` | quote }}
            {{- end }}
          zfs:
            {{- if .Values.cluster.storage.truenas.zfs.cli }}
            cli:
              {{- if .Values.cluster.storage.truenas.zfs.cli.sudoEnabled }}
              sudoEnabled: {{ .Values.cluster.storage.truenas.zfs.cli.sudoEnabled }}
              {{- end }}
              {{- if .Values.cluster.storage.truenas.zfs.cli.paths }}
              paths:
                {{- if .Values.cluster.storage.truenas.zfs.cli.paths.zfs }}
                zfs: {{ .Values.cluster.storage.truenas.zfs.cli.paths.zfs | quote }}
                {{- end }}
                {{- if .Values.cluster.storage.truenas.zfs.cli.paths.zpool }}
                zpool: {{ .Values.cluster.storage.truenas.zfs.cli.paths.zpool | quote }}
                {{- end }}
                {{- if .Values.cluster.storage.truenas.zfs.cli.paths.sudo }}
                sudo: {{ .Values.cluster.storage.truenas.zfs.cli.paths.sudo | quote }}
                {{- end }}
                {{- if .Values.cluster.storage.truenas.zfs.cli.paths.chroot }}
                chroot: {{ .Values.cluster.storage.truenas.zfs.cli.paths.chroot | quote }}
                {{- end }}
              {{- end }}
            {{- end }}
            datasetParentName: {{ .Values.cluster.storage.truenas.zfs.datasetParentName | quote }}
            detachedSnapshotsDatasetParentName: {{ .Values.cluster.storage.truenas.zfs.detachedSnapshotsDatasetParentName | quote }}
            zvolCompression: {{ .Values.cluster.storage.truenas.zfs.zvolCompression | quote }}
            zvolDedup: {{ .Values.cluster.storage.truenas.zfs.zvolDedup | quote }}
            zvolEnableReservation: {{ .Values.cluster.storage.truenas.zfs.zvolEnableReservation }}
            zvolBlocksize: {{ .Values.cluster.storage.truenas.zfs.zvolBlocksize | quote }}
          iscsi:
            targetPortal: {{ .Values.cluster.storage.truenas.iscsi.targetPortal | quote }}
            {{- if .Values.cluster.storage.truenas.iscsi.targetPortals }}
            targetPortals: {{ .Values.cluster.storage.truenas.iscsi.targetPortals | toJson }}
            {{- else }}
            targetPortals: []
            {{- end }}
            {{- if .Values.cluster.storage.truenas.iscsi.interface }}
            interface: {{ .Values.cluster.storage.truenas.iscsi.interface | quote }}
            {{- end }}
            {{- if .Values.cluster.storage.truenas.iscsi.namePrefix }}
            namePrefix: {{ .Values.cluster.storage.truenas.iscsi.namePrefix | quote }}
            {{- end }}
            {{- if .Values.cluster.storage.truenas.iscsi.nameSuffix }}
            nameSuffix: {{ .Values.cluster.storage.truenas.iscsi.nameSuffix | quote }}
            {{- end }}
            targetGroups:
            {{- range .Values.cluster.storage.truenas.iscsi.targetGroups }}
              - targetGroupPortalGroup: {{ .targetGroupPortalGroup }}
                targetGroupInitiatorGroup: {{ .targetGroupInitiatorGroup }}
                targetGroupAuthType: {{ .targetGroupAuthType }}
                {{- if .targetGroupAuthGroup }}
                targetGroupAuthGroup: {{ .targetGroupAuthGroup | quote }}
                {{- else }}
                targetGroupAuthGroup: ""
                {{- end }}
            {{- end }}
            extentInsecureTpc: {{ .Values.cluster.storage.truenas.iscsi.extentInsecureTpc }}
            extentXenCompat: {{ .Values.cluster.storage.truenas.iscsi.extentXenCompat }}
            extentDisablePhysicalBlocksize: {{ .Values.cluster.storage.truenas.iscsi.extentDisablePhysicalBlocksize }}
            extentBlocksize: {{ .Values.cluster.storage.truenas.iscsi.extentBlocksize }}
            extentRpm: {{ .Values.cluster.storage.truenas.iscsi.extentRpm | quote }}
            extentAvailThreshold: {{ .Values.cluster.storage.truenas.iscsi.extentAvailThreshold }}
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: {{ .Values.cluster.storage.truenas.secretKeys.apiKey }}
    - secretKey: TRUENAS_SSH_PASSWORD
      remoteRef:
        key: {{ .Values.cluster.storage.truenas.secretKeys.sshPassword }}
    - secretKey: TRUENAS_PASSWORD
      remoteRef:
        key: {{ .Values.cluster.storage.truenas.secretKeys.truenasPassword }}
