---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-truenas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-truenas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            protocol: {{ .Values.cluster.storage.truenas.server.protocol }}
            host: {{ .Values.cluster.storage.truenas.server.host }}
            port: {{ .Values.cluster.storage.truenas.server.port }}
            apiKey: {{ `"{{ .TRUENAS_API_KEY }}"` }}
            allowInsecure: {{ .Values.cluster.storage.truenas.server.allowInsecure }}
            apiVersion: 2
          zfs:
            datasetParentName: {{ .Values.cluster.storage.truenas.zfs.datasetParentName | quote }}
            detachedSnapshotsDatasetParentName: {{ .Values.cluster.storage.truenas.zfs.detachedSnapshotsDatasetParentName | quote }}
            zvolBlocksize: {{ .Values.cluster.storage.truenas.zfs.zvolBlocksize | quote }}
            zvolCompression: {{ .Values.cluster.storage.truenas.zfs.zvolCompression | quote }}
            thinProvision: true
          iscsi:
            iqnPrefix: {{ .Values.cluster.name | quote }}
            namePrefix: {{ printf "%s-" .Values.cluster.name | quote }}
            nameSuffix: ""
            targetPortal: {{ .Values.cluster.storage.truenas.iscsi.targetPortal | quote }}
            targetPortals: []
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
                targetGroupAuthGroup: ""
            extentCommentTemplate: "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            extentUseThinProvisioning: true
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 4096
            extentRpm: "SSD"
            discoveryCHAPAuth: false
            chap: "disabled"
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: {{ .Values.cluster.storage.truenas.secretKeys.apiKey }}
