---
# Base role application - contains core cluster components
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - kind: Application
    group: argoproj.io
    jsonPointers:
    - /spec/syncPolicy/automated
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: roles/base
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        # SNO-specific base component overrides
        goldilocks:
          enabled: false  # Disable on SNO to save resources
        gatus:
          enabled: true
        spec:
{{ .Values.spec | toYaml | nindent 10 }}
{{ .Values.config | toYaml | nindent 8 }}
