---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: "keepalived-operator/lan"
spec:
  type: ClusterIP
  externalIPs:
    - {{ .Values.jellyfin.network.ip }}
  ports:
    - name: http
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
    - name: discovery
      port: 7359
      targetPort: 7359
      protocol: UDP
    - name: dlna
      port: 1900
      targetPort: 1900
      protocol: UDP
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
