cluster:
  top_level_domain: roybales.com
  name: cluster
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: nas
        path: /volume1/media

application:
  name: Gatus
  group: Infrastructure
  icon: game-icons:spyglass
  iconColor: ""
  image: "https://gatus.io/img/logo-with-light-text.svg"
  description: "Service health monitoring"
  port: 8080
  location: 0
  tags: admin

pods:
  sidecar:
    image:
      repository: ghcr.io/kiwigrid/k8s-sidecar
      # renovate: datasource=docker depName=ghcr.io/kiwigrid/k8s-sidecar versioning=semver
      tag: 1.30.11
      pullPolicy: IfNotPresent
    env:
      # Service links are disabled in the pod spec, so explicitly set the API server endpoint.
      FOLDER: /config
      LABEL: gatus.io/enabled
      LABEL_VALUE: "true"
      NAMESPACE: ALL
      RESOURCE: configmap
      METHOD: WATCH
      UNIQUE_FILENAMES: "true"
      KUBERNETES_SERVICE_HOST: kubernetes.default.svc
      KUBERNETES_SERVICE_PORT: "443"
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 256Mi

  main:
    image:
      repository: twinproduction/gatus
      # renovate: datasource=docker depName=twinproduction/gatus versioning=semver
      tag: v5.26.0
      pullPolicy: IfNotPresent
    env: {}
    resources: {}

config:
  web:
    port: 8080
  storage:
    type: sqlite
    path: /data/sqlite.db
    caching: true
  metrics: true
  debug: false
  ui:
    title: Status | Gatus
    header: Status
  endpoints:
    - name: google
      group: external
      url: https://google.com
      interval: 60s
      conditions:
        - "[STATUS] == 200"
        - "[BODY] == pat(*Google*)"
