apiVersion: v2
description: A Helm chart for the AMD GPU Device Plugin on OpenShift
name: amd-gpu-operator
version: 1.0.0
kubeVersion: ">=1.22.0-0"

maintainers:
  - name: Roy Bales
    email: rbales79@gmail.com
