cluster:
  top_level_domain: example.com
  name: cluster
  storage:
    democratic-csi:
      httpConnection:
        host: truenas.roybales.com
        port: 443
        protocol: https
        allowInsecure: true
      iscsi:
        targetPortal: "truenas.roybales.com:3260"
        iqnPrefix: "iqn.2005-10.org.freenas.ctl"
      secretKeys:
        apiKey: TRUENAS_API_KEY
    config:
      storageClassName: truenas-iscsi

democratic-csi:
  driver:
    existingConfigSecret: democratic-csi-truenas-config
    config:
      driver: freenas-api-iscsi
      httpConnection:
        protocol: https
        allowInsecure: true
      zfs:
        datasetParentName: "volume1/iscsi/test/vols"
        detachedSnapshotsDatasetParentName: "volume1/iscsi/test/snaps"
        zvolBlocksize: "16K"
        zvolCompression: "lz4"
        thinProvision: true
      iscsi:
        targetPortals: []
        targetGroups:
          - targetGroupPortalGroup: 1
            targetGroupInitiatorGroup: 1
            targetGroupAuthType: None
            targetGroupAuthGroup: ""
        extentUseThinProvisioning: true
        extentDisablePhysicalBlocksize: true
        extentBlocksize: 4096
        extentRpm: "SSD"
        discoveryCHAPAuth: false
        chap: "disabled"

  csiDriver:
    name: "org.democratic-csi.truenas-iscsi"

  node:
    rbac:
      openshift:
        privileged: true
    hostPID: true

  controller:
    rbac:
      openshift:
        privileged: true
    driver:
      image:
        repository: democraticcsi/democratic-csi
        tag: next
        pullPolicy: IfNotPresent
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true

  storageClasses:
    - name: truenas-iscsi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
        csi.storage.k8s.io/fstype: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

  volumeSnapshotClasses:
    - name: truenas-iscsi
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      deletionPolicy: Delete
      parameters:
      secrets:
        snapshotter-secret:
