cluster:
  top_level_domain: example.com
  name: cluster
  storage:
    democratic-csi:
      httpConnection:
        host: truenas.roybales.com
        port: 80
        protocol: http
        allowInsecure: true
      sshConnection:
        host: truenas.roybales.com
        port: 22
      iscsi:
        targetPortal: "truenas.roybales.com:5000"
      secretKeys:
        apiKey: TRUENAS_API_KEY
    config:
      storageClassName: truenas-iscsi

democratic-csi:
  driver:
    existingConfigSecret: democratic-csi-tnas-config
    config:
      driver: freenas-api-iscsi
      zfs:
        datasetParentName: volume1/iscsi/test/vols
        detachedSnapshotsDatasetParentName: volume1/iscsi/test/snaps
        zvolCompression: ""
        zvolDedup: ""
        zvolEnableReservation: false
        zvolBlocksize: ""
      iscsi:
        interface: ""
        namePrefix: csi-
        nameSuffix: "-clusterb"
        targetGroups:
          - targetGroupPortalGroup: 1
            targetGroupInitiatorGroup: 2
            targetGroupAuthType: None
            targetGroupAuthGroup: ""
        extentInsecureTpc: true
        extentXenCompat: false
        extentDisablePhysicalBlocksize: true
        extentBlocksize: 512
        extentRpm: "SSD"
        extentAvailThreshold: 0

  csiDriver:
    name: "org.democratic-csi.iscsi-truenas"

  node:
    rbac:
      openshift:
        privileged: true
    driver:
      localtimeHostPath: false

  controller:
    rbac:
      openshift:
        privileged: true
    externalResizer:
      enabled: true
    externalSnapshotter:
      enabled: true

  storageClasses:
    - name: truenas-iscsi
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4

      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

  volumeSnapshotClasses:
    - name: truenas-iscsi
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
      deletionPolicy: Delete
      parameters:
      secrets:
        snapshotter-secret:
