apiVersion: v2
description: A Helm chart for OpenShift Vertical Pod Autoscaler operator
name: vertical-pod-autoscaler
version: 1.0.0
kubeVersion: ">=1.22.0-0"

maintainers:
  - name: Roy Bales
    email: rbales79@gmail.com
