cluster:
  top_level_domain: example.com
  name: openshift
  admin_email: admin@example.com
  timezone: America/New_York

application:
  name: n8n
  group: AI
  image: https://docs.n8n.io/_images/n8n-docs-icon.svg
