apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vertical-pod-autoscaler-operator-group
  namespace: openshift-vertical-pod-autoscaler
spec:
  targetNamespaces:
  - openshift-vertical-pod-autoscaler
