cluster:
  top_level_domain: roybales.com
  name: cluster
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
    config:
      storageClassName: truenas-iscsi
    media:
      nfs:
        server: truenas.roybales.com
        path: /mnt/volume1/media

application:
  name: Overseerr
  group: Media
  icon: cbi:overseerr
  iconColor: ""
  image: "https://raw.githubusercontent.com/sct/overseerr/develop/public/logo_full.svg"
  description: "Helps you find media you want to watch"
  port: 5055
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/sct/overseerr
      # renovate: datasource=docker depName=ghcr.io/sct/overseerr versioning=semver
      tag: 1.34.0
      pullPolicy: IfNotPresent

# Gatus monitoring
gatus:
  enabled: false
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 3000"
