{{- if .Values.acm.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    name: open-cluster-management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: {{ .Values.acm.channel | default "release-2.10" }}
  installPlanApproval: {{ .Values.acm.installPlanApproval | default "Automatic" }}
  name: advanced-cluster-management
  source: {{ .Values.acm.source | default "redhat-operators" }}
  sourceNamespace: {{ .Values.acm.sourceNamespace | default "openshift-marketplace" }}
{{- end }}
