---
# Patch the cert-manager controller deployment to use Cloudflare DNS servers
# This ensures DNS-01 challenges are validated against authoritative nameservers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  template:
    spec:
      # Configure pod to use Cloudflare's public DNS servers
      # This overrides the cluster's default DNS configuration
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "1.1.1.1"  # Cloudflare primary DNS
          - "1.0.0.1"  # Cloudflare secondary DNS
        searches:
          - cert-manager.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
          - name: timeout
            value: "2"
          - name: attempts
            value: "2"
