---
# ConfigMap to configure cert-manager to use specific DNS servers for DNS-01 challenges
# This ensures cert-manager can properly validate DNS records created in Cloudflare
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-dns-config
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  # Use Cloudflare's DNS servers for DNS-01 challenge validation
  # This ensures cert-manager queries the authoritative DNS servers
  # where the ACME challenge records are created
  dns-servers: "1.1.1.1:53,1.0.0.1:53"
