---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.cluster.admin_email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
      dns01:
        cnameStrategy: Follow
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
        # Use Cloudflare's public DNS servers for DNS-01 challenge validation
        # This ensures cert-manager queries authoritative nameservers
        recursiveNameservers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        recursiveNameserversOnly: true
