spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

config:
  cluster:
    top_level_domain: roybales.com
    name: cluster
    admin_email: YOUR_EMAIL
    timezone: YOUR_TIMEZONE
