---
# Test ExternalSecret to verify Infisical integration
# Deploy this to test if secrets are being pulled correctly
#
# Usage:
#   1. Add a test secret to Infisical:
#      Project: hub-cluster
#      Environment: prod
#      Path: /TEST
#      Key: TEST_SECRET
#      Value: "Hello from Infisical!"
#
#      IMPORTANT: In Infisical, make sure you're adding the secret in a folder
#      Create a folder called "TEST" and add the secret inside it
#      The key should be exactly: TEST_SECRET
#      The value should be: Hello from Infisical!
#
#   2. Deploy this manifest:
#      oc apply -f test-externalsecret.yaml
#
#   3. Check the ExternalSecret status:
#      oc describe externalsecret test-secret -n default
#
#   4. View the generated secret:
#      oc get secret test-secret -n default -o yaml
#
#   5. Decode and view the secret value:
#      oc get secret test-secret -n default -o jsonpath='{.data.test-key}' | base64 -d
#
#   6. Clean up when done:
#      oc delete externalsecret test-secret -n default
#      oc delete secret test-secret -n default

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
    - secretKey: test-key          # <- what you'll read from the K8s Secret
      remoteRef:
        key: TEST_SECRET      # <- Infisical folder/key
