cluster:
  top_level_domain: roybales.com
  name: cluster
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
    config:
      storageClassName: truenas-iscsi
    media:
      nfs:
        server: truenas.roybales.com
        path: /mnt/volume1/media

application:
  name: Sonarr
  group: Media
  icon: cbi:sonarr
  iconColor: ""
  image: "https://raw.githubusercontent.com/Sonarr/Sonarr/v5-develop/Logo/256.png"
  description: "TV Series management"
  port: 8989
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/home-operations/sonarr
      # renovate: datasource=docker depName=ghcr.io/home-operations/sonarr versioning=semver
      tag: 4.0.15
      pullPolicy: IfNotPresent
    env:
      COMPlus_EnableDiagnostics: "0"
      SONARR__APP__INSTANCENAME: Sonarr
      SONARR__AUTH__METHOD: External
      SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
      SONARR__LOG__LEVEL: info

# Gatus monitoring
gatus:
  enabled: true
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 3000"
