cluster:
  top_level_domain: roybales.com
  name: cluster
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
    #config:
    #  storageClassName: synology-iscsi
    media:
      nfs:
        server: truenas.roybales.com
        path: /mnt/volume1/media

application:
  name: Huntarr
  group: Media
  icon: f7:scope
  iconColor: ""
  image: ""
  description: "Searches for missing items"
  port: 9705
  location: 0

pods:
  main:
    image:
      repository: ghcr.io/plexguide/huntarr
      # renovate: datasource=docker depName=ghcr.io/plexguide/huntarr versioning=semver
      tag: 8.2.10
      pullPolicy: IfNotPresent

# Gatus monitoring
gatus:
  enabled: false
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 3000"
