spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

config:
  cluster:
    top_level_domain: roybales.com
    name: sno
    admin_email: YOUR_EMAIL
    timezone: America/New_York
    storage:
      democratic-csi:
        httpConnection:
          host: truenas.roybales.com
          port: 3260
        iscsi:
          targetPortal: truenas.roybales.com
      config:
        storageClassName: truenas-iscsi
      media:
        nfs:
          server: truenas.roybales.com
          path: /mnt/volume1/sno

  plex:
    network:
      ip: 192.168.1.205

  emqx:
    network:
      ip: 192.168.1.204

  certificates:
    letsencrypt:
      issuer: production

  externalSecrets:
    secret: infisical-auth-secret
    infisical:
      projectSlug: hub
      environmentSlug: prod

  network:
    lan:
      defaultGateway: 192.168.1.1
