# Cronjob configuration
cronjob:
  # Schedule for the cronjob (cron format)
  # Default: every hour
  schedule: "0 * * * *"

# Container image configuration
image:
  repository: registry.redhat.io/openshift4/ose-cli
  tag: v4.15
  pullPolicy: IfNotPresent
