spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rbales79/argo-apps
    targetRevision: HEAD

config:
  cluster:
    top_level_domain: roybales.com
    name: sno
    admin_email: rbales79@gmail.com
    timezone: America/New_York
    storage:
      truenas:
        zfs:
          datasetParentName: "volume1/iscsi/sno/vols"
          detachedSnapshotsDatasetParentName: "volume1/iscsi/sno/snaps"
        iscsi:
          namePrefix: "sno-"
        secretKeys:
          apiKey: TRUENAS_API_KEY
          sshPassword: TRUENAS_SSH_PASSWORD
          truenasPassword: TRUENAS_PASSWORD
      config:
        storageClassName: truenas-iscsi
      media:
        nfs:
          server: truenas.roybales.com
          path: /mnt/volume1/media

  plex:
    network:
      ip: 192.168.1.200

  emqx:
    network:
      ip: 192.168.1.201

  certificates:
    letsencrypt:
      issuer: production

  externalSecrets:
    secret: infisical-auth-secret
    infisical:
      projectSlug: hub
      environmentSlug: prod

  network:
    lan:
      defaultGateway: 192.168.1.1

  # ArgoCD Resource Configuration
  # Configure resource limits for OpenShift GitOps components
  # Increase these values for clusters managing many applications
  argocd:
    enabled: true
    # Application Controller - Main reconciliation engine
    controller:
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: "4"
          memory: 8Gi
    # ApplicationSet Controller - Manages ApplicationSets
    applicationSet:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "2"
          memory: 1Gi
    # Repo Server - Git repository operations
    repo:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
    # Server - API and UI
    server:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    # Redis - Caching
    redis:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    # Dex - SSO/OAuth
    dex:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
