apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}-tweaks
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  goTemplate: true
  generators:
    - list:
        elements:
        {{- if index .Values "snapshot-finalizer-remover" "enabled" }}
        - name: snapshot-finalizer-remover
          group: tweaks
        {{- end }}
        {{- if index .Values "disable-master-secondary-interfaces" "enabled" }}
        - name: disable-master-secondary-interfaces
          group: tweaks
          createNamespace: false
        {{- end }}
        {{- if index .Values "disable-worker-secondary-interfaces" "enabled" }}
        - name: disable-worker-secondary-interfaces
          group: tweaks
          createNamespace: false
        {{- end }}
  template:
    metadata:
      name: '{{ "{{" }} .name {{ "}}" }}'
      namespace: "openshift-gitops"
    spec:
      ignoreDifferences:
      - kind: Application
        group: argoproj.io
        jsonPointers:
        - /spec/syncPolicy
      project: default
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: "openshift-gitops"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        path: charts/{{ "{{" }} .group {{ "}}" }}/{{ "{{" }} .name {{ "}}" }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        helm:
          valuesObject:
            spec:
{{ .Values.spec | toYaml | nindent 14 }}
{{ .Values.config | toYaml | nindent 12 }}
