---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    route.openshift.io/termination: "edge"
  name: emqx
spec:
  host: "emqx.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
  path: /
  to:
    kind: Service
    name: emqx-dashboard
    weight: 100
  port:
    targetPort: dashboard
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
