---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: freenas-iscsi
          httpConnection:
            allowInsecure: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "allowInsecure" }}
            host: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "host" }}
            port: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "port" }}
            protocol: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "protocol" }}
            apiKey: {{ printf "{{ .%s }}" (index .Values "cluster" "storage" "democratic-csi" "secretKeys" "apiKey") }}
            connectTimeout: {{ index .Values "democratic-csi" "driver" "config" "httpConnection" "connectTimeout" }}
            readTimeout: {{ index .Values "democratic-csi" "driver" "config" "httpConnection" "readTimeout" }}
            serialize: true
            session: {{ .Values.cluster.name }}-democratic-csi
          zfs:
            datasetParentName: {{ index .Values "democratic-csi" "driver" "config" "zfs" "datasetParentName" }}
            detachedSnapshotsDatasetParentName: {{ index .Values "democratic-csi" "driver" "config" "zfs" "detachedSnapshotsDatasetParentName" }}
            datasetNameTemplate: '{{ "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}" }}/{{ "{{ parameters.[csi.storage.k8s.io/pvc/name] }}" }}'
{{- if index .Values "democratic-csi" "driver" "config" "zfs" "datasetProperties" }}
{{ toYaml (index .Values "democratic-csi" "driver" "config" "zfs" "datasetProperties") | indent 12 }}
{{- else }}
            datasetProperties: {}
{{- end }}
          iscsi:
            targetPortal: {{ index .Values "cluster" "storage" "democratic-csi" "iscsi" "targetPortal" }}
{{- if index .Values "cluster" "storage" "democratic-csi" "iscsi" "targetPortals" }}
            targetPortals:
{{ toYaml (index .Values "cluster" "storage" "democratic-csi" "iscsi" "targetPortals") | indent 14 }}
{{- else }}
            targetPortals: []
{{- end }}
            targetPortalPort: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetPortalPort" }}
            targetIQN: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetIQN" }}
            interface: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "interface" | quote }}
            extentSize: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentSize" }}
            discoveryAuthGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "discoveryAuthGroup" }}
            namePrefix: {{ printf "%s-" .Values.cluster.name | quote }}
            nameSuffix: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "nameSuffix" | quote }}
  data:
    - secretKey: {{ index .Values "cluster" "storage" "democratic-csi" "secretKeys" "apiKey" }}
      remoteRef:
        key: {{ index .Values "cluster" "storage" "democratic-csi" "secretKeys" "apiKey" }}
