---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-tnas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-tnas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
{{- $values := .Values -}}
{{- $cluster := default (dict) $values.cluster -}}
{{- $storageRoot := default (dict) (index $cluster "storage") -}}
{{- $storage := default (dict) (index $storageRoot "democratic-csi") -}}
{{- $secretKeys := default (dict) (index $storage "secretKeys") -}}
{{- $apiKeyName := default "TRUENAS_API_KEY" (index $secretKeys "apiKey") -}}
{{- $driverConfig := mustDeepCopy (default (dict) (index $values "democratic-csi" "driver" "config")) -}}
{{- $httpConfig := dict -}}
{{- range $key, $value := default (dict) (index $driverConfig "httpConnection") }}
{{- $_ := set $httpConfig $key $value }}
{{- end }}
{{- range $key, $value := default (dict) (index $storage "httpConnection") }}
{{- $_ := set $httpConfig $key $value }}
{{- end }}
{{- $_ := set $httpConfig "apiKey" (printf "{{ index .Data \"%s\" | quote }}" $apiKeyName) }}
{{- $_ := set $driverConfig "httpConnection" $httpConfig }}
{{- $iscsiConfig := dict -}}
{{- range $key, $value := default (dict) (index $driverConfig "iscsi") }}
{{- $_ := set $iscsiConfig $key $value }}
{{- end }}
{{- range $key, $value := default (dict) (index $storage "iscsi") }}
{{- $_ := set $iscsiConfig $key $value }}
{{- end }}
{{- $_ := set $driverConfig "iscsi" $iscsiConfig }}
{{- $zfsConfig := dict -}}
{{- range $key, $value := default (dict) (index $driverConfig "zfs") }}
{{- $_ := set $zfsConfig $key $value }}
{{- end }}
{{- $_ := set $driverConfig "zfs" $zfsConfig }}
  driver-config-file.yaml: |
{{ toYaml $driverConfig | indent 10 }}
  data:
    - secretKey: {{ $apiKeyName }}
      remoteRef:
        key: {{ $apiKeyName }}
