---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-tnas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-tnas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
{{- $storage := default (dict) (index .Values "cluster" "storage" "democratic-csi") -}}
{{- $http := default (dict) (index $storage "httpConnection") -}}
{{- $storageIscsi := default (dict) (index $storage "iscsi") -}}
{{- $secretKeys := default (dict) (index $storage "secretKeys") -}}
{{- $apiKeyName := default "TRUENAS_API_KEY" (index $secretKeys "apiKey") -}}
{{- $driverConfig := default (dict) (index .Values "democratic-csi" "driver" "config") -}}
{{- $httpConfig := default (dict) (index $driverConfig "httpConnection") -}}
{{- $zfsConfig := default (dict) (index $driverConfig "zfs") -}}
{{- $zfsProperties := default (dict) (index $zfsConfig "datasetProperties") -}}
{{- $iscsiConfig := default (dict) (index $driverConfig "iscsi") -}}
{{- $targetPortals := default (list) (index $storageIscsi "targetPortals") -}}
        driver-config-file.yaml: |
          driver: freenas-iscsi
          httpConnection:
            allowInsecure: {{ index $http "allowInsecure" }}
            host: {{ index $http "host" }}
            port: {{ index $http "port" }}
            protocol: {{ index $http "protocol" }}
            apiKey: {{ printf "\"{{ .%s }}\"" $apiKeyName }}
            connectTimeout: {{ index $httpConfig "connectTimeout" }}
            readTimeout: {{ index $httpConfig "readTimeout" }}
            serialize: true
            session: {{ .Values.cluster.name }}-democratic-csi
          zfs:
            datasetParentName: {{ index $zfsConfig "datasetParentName" }}
            detachedSnapshotsDatasetParentName: {{ index $zfsConfig "detachedSnapshotsDatasetParentName" }}
            datasetNameTemplate: {{ printf "'{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}'" }}
{{- if $zfsProperties }}
{{ toYaml $zfsProperties | indent 12 }}
{{- else }}
            datasetProperties: {}
{{- end }}
          iscsi:
            targetPortal: {{ index $storageIscsi "targetPortal" }}
{{- if $targetPortals }}
            targetPortals:
{{ toYaml $targetPortals | indent 14 }}
{{- else }}
            targetPortals: []
{{- end }}
            targetPortalPort: {{ index $iscsiConfig "targetPortalPort" }}
            targetIQN: {{ index $iscsiConfig "targetIQN" }}
            interface: {{ index $iscsiConfig "interface" | quote }}
            extentSize: {{ index $iscsiConfig "extentSize" }}
            discoveryAuthGroup: {{ index $iscsiConfig "discoveryAuthGroup" }}
            namePrefix: {{ printf "%s-" .Values.cluster.name | quote }}
            nameSuffix: {{ index $iscsiConfig "nameSuffix" | quote }}
  data:
    - secretKey: {{ $apiKeyName }}
      remoteRef:
        key: {{ $apiKeyName }}
