---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
{{- $clusterName := default "cluster" .Values.cluster.name -}}
{{- $storage := default (dict) (index .Values "cluster" "storage" "democratic-csi") -}}
{{- $httpValues := default (dict) (index $storage "httpConnection") -}}
{{- $iscsiValues := default (dict) (index $storage "iscsi") -}}
{{- $secretKeys := default (dict) (index $storage "secretKeys") -}}
{{- $apiKeySecret := default "TRUENAS_API_KEY" (index $secretKeys "apiKey") -}}
{{- $config := deepCopy (default (dict) (index .Values "democratic-csi" "driver" "config")) -}}
{{- $httpConfig := default (dict) (index $config "httpConnection") -}}
{{- $_ := set $config "httpConnection" $httpConfig -}}
{{- range $key, $value := $httpValues }}
{{- $_ := set $httpConfig $key $value -}}
{{- end }}
{{- $_ := set $httpConfig "apiKey" (printf "{{ .%s }}" $apiKeySecret) -}}
{{- $_ := set $httpConfig "serialize" true -}}
{{- $_ := set $httpConfig "session" (printf "%s-democratic-csi" $clusterName) -}}
{{- $iscsiConfig := default (dict) (index $config "iscsi") -}}
{{- $_ := set $config "iscsi" $iscsiConfig -}}
{{- range $key, $value := $iscsiValues }}
{{- $_ := set $iscsiConfig $key $value -}}
{{- end }}
{{- $_ := set $iscsiConfig "namePrefix" (printf "%s-" $clusterName) -}}
{{- if not (hasKey $iscsiConfig "targetPortals") }}
{{- $targetPortal := index $iscsiValues "targetPortal" | default "" -}}
{{- if $targetPortal }}
{{- $_ := set $iscsiConfig "targetPortals" (list $targetPortal) -}}
{{- else }}
{{- $_ := set $iscsiConfig "targetPortals" (list) -}}
{{- end }}
{{- end }}
{{- if not (hasKey $iscsiConfig "targetPortalPort") }}
{{- $_ := set $iscsiConfig "targetPortalPort" 3260 -}}
{{- end }}
{{- if not (hasKey $iscsiConfig "nameSuffix") }}
{{- $_ := set $iscsiConfig "nameSuffix" "" -}}
{{- end }}
{{ toYaml $config | indent 10 }}
  data:
    - secretKey: {{ $apiKeySecret }}
      remoteRef:
        key: {{ $apiKeySecret }}
