---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-tnas-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: democratic-csi-tnas-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          instance_id:
          httpConnection:
            protocol: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "protocol" }}
            host: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "host" }}
            port: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "port" }}
            apiKey: {{ `"{{ .TRUENAS_API_KEY }}"` }}
            allowInsecure: {{ index .Values "cluster" "storage" "democratic-csi" "httpConnection" "allowInsecure" }}
            serialize: true
          sshConnection:
            host: {{ index .Values "cluster" "storage" "democratic-csi" "sshConnection" "host" }}
            username: {{ `"{{ .TRUENAS_SSH_USERNAME }}"` }}
            password: {{ `"{{ .TRUENAS_SSH_PASSWORD }}"` }}
            port: {{ index .Values "cluster" "storage" "democratic-csi" "sshConnection" "port" }}
          zfs:
            datasetParentName: {{ index .Values "democratic-csi" "driver" "config" "zfs" "datasetParentName" }}
            detachedSnapshotsDatasetParentName: {{ index .Values "democratic-csi" "driver" "config" "zfs" "detachedSnapshotsDatasetParentName" }}
            zvolCompression: {{ index .Values "democratic-csi" "driver" "config" "zfs" "zvolCompression" | quote }}
            zvolDedup: {{ index .Values "democratic-csi" "driver" "config" "zfs" "zvolDedup" | quote }}
            zvolEnableReservation: {{ index .Values "democratic-csi" "driver" "config" "zfs" "zvolEnableReservation" }}
            zvolBlocksize: {{ index .Values "democratic-csi" "driver" "config" "zfs" "zvolBlocksize" | quote }}
          iscsi:
            targetPortal: {{ index .Values "cluster" "storage" "democratic-csi" "iscsi" "targetPortal" | quote }}
            targetPortals: []
            interface: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "interface" | quote }}
            namePrefix: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "namePrefix" }}
            nameSuffix: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "nameSuffix" | quote }}
            targetGroups:
              - targetGroupPortalGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupPortalGroup" }}
                targetGroupInitiatorGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupInitiatorGroup" }}
                targetGroupAuthType: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupAuthType" }}
                targetGroupAuthGroup: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "targetGroups" 0 "targetGroupAuthGroup" | quote }}
            extentInsecureTpc: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentInsecureTpc" }}
            extentXenCompat: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentXenCompat" }}
            extentDisablePhysicalBlocksize: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentDisablePhysicalBlocksize" }}
            extentBlocksize: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentBlocksize" }}
            extentRpm: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentRpm" | quote }}
            extentAvailThreshold: {{ index .Values "democratic-csi" "driver" "config" "iscsi" "extentAvailThreshold" }}
  data:
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: TRUENAS_API_KEY
    - secretKey: TRUENAS_SSH_USERNAME
      remoteRef:
        key: TRUENAS_SSH_USERNAME
    - secretKey: TRUENAS_SSH_PASSWORD
      remoteRef:
        key: TRUENAS_SSH_PASSWORD
