cluster:
  top_level_domain: roybales.com
  name: cluster
  admin_email: rbales79@gmail.com
  timezone: America/New_York
  storage:
     config:
       storageClassName: truenas-iscsi
    media:
      nfs:
        server: truenas.roybales.com
        path: /mnt/volume1/backup/test

application:
  name: Kasten K10
  group: Infrastructure
  icon: material-symbols:backup-outline
  iconColor: ""
  image: "https://docs.kasten.io/img/favicon_228x228px.png"
  description: "Manages backups and disaster recovery"
  location: 0
  tags: admin

  #ns - kasten-io

kasten:
  # Storage class for Kasten K10 persistence
  # If not set, will use cluster.storage.config.storageClassName
  # If neither is set, Kubernetes will use the default storage class
  storageClass: ""

  # Custom applications to exclude from Kasten K10 backups
  # OpenShift system namespaces are automatically excluded via openshift-excluded-apps.yaml
  excludedApps:
  - object-lease-operator-system
